# Change baseurl before deploy
baseurl = "https://www.ytom.cc"
languageCode = "zh-cn"
title = "ytom"

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
defaultContentLanguage = "zh-cn"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = true

# Change it to your Disqus shortname before using
disqusShortname = "hugo-theme-stack"

verbose = true
verboseLog = true
logLevel = "debug"

[pagination]
pagerSize = 5

[server]
enableReload = true
watch = true
